In [1]:
from tools import *

<div dir="rtl" lang="he" xml:lang="he">

# תנועה קולקטיבית - מודלים טובים ומודלים טובים יותר


תנועה קולקטיבית היא אחד התופעות המענייונות ביותר,
קבוצה של בעלי חיים נעה במרחב בצורה כאילו מאורגנת ללא שוב מנהיג נראה לעין. 
אלו מודלים יכולים להסביר את התנועה הזאת?
והאם נמצא דרך להשוות בן המודלים האלו?

<div dir="rtl" lang="he" xml:lang="he">

## מודל פשוט - vicsek
המודל הבסיסי ביותר, הוא המודל של 
vicsek
כל בעל חיים מתואר ע"י מיקומו,
מסומן ב
$\vec{r}_i \in R^3$
ווקטור הכיוון שלו שמסומן ב
$\vec{v}_i \in R^2$
כאשר כלל העידכון הוא הליכה בכיון הממוצע. 
ע"י חישוב וקטור הכיון של השכנים, מתואר ע"י המשוואה 
$$
\\ \vec{S}_i = \sum_{j\in \text{Neg}(i)}{\vec{v}_j}
\\ \vec{v}_i = \frac{\vec{S}_i}{|\vec{S}_i|}*v_0
$$
כאשר 
$v_0$ 
הוא גודל קבוע המייצג את מהירות בעל החיים. 




$$
\\ \vec{S} = \sum_{j\in \text{Neg}(i)}{\vec{v}_j}
\\ \vec{v}_i = \frac{\vec{S}}{|\vec{S}|}*v_0
$$

In [66]:
def get_avrage_velocity(data: TensorType, radios: float = 5.0) -> TensorType:
    """get the avrage velocity of the input data

    Args:
        data (TensorType): tensor (N,5) of x,y,z,theta,phi
        radios (float, optional): radios of . Defaults to 5.0.

    Returns:
        TensorType: tensor (N,2) new velocity of the input data
    """
    # for each data point, get the distance from any other data point
    dis_mat = torch.stack(
        [torch.linalg.norm(data[i, :3] - data[:, :3], dim=1) for i in range(len(data))]
    )
    # dis_mat = dis_mat + dis_mat.T
    # return new_data
    # for each data point, get the avrage velocity of the data points that are in the radios
    new_velocity = torch.stack(
        [data[dis_mat[i] < radios, 3:].mean(dim=0) for i in range(len(data))]
    )
    return new_velocity

In [70]:
data = torch.rand(1000, 5)
data[:, 3:] = data[:, 3:] * 360
data[:, :3] = data[:, :3] * 20 - 10
print(get_avrage_velocity(data))
print(data[0, 3:])
# torch.linalg.norm(data[:, :3]-data[1, :3],dim=1)

tensor([[187.1057, 188.4845],
        [192.2007, 176.6724],
        [195.1164, 204.1816],
        ...,
        [175.3696, 192.0084],
        [176.1100, 157.1403],
        [199.5588, 157.6523]])
tensor([ 66.8445, 173.6481])


In [5]:
torch.tensor([i for i in range(10)])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
for r in torch.logspace(0, 10**7,10):
    print(
        f"list comp = {timeit.timeit(torch.tensor([i for i in range(int(r))]), number=100)}"
    )
    print(f"torch range = {timeit.timeit(torch.range(int(r)), number=100)}")

ValueError: stmt is neither a string nor callable